name: Cloud Native Sustainability Week Local Meetup Tracking Issue
description: Use this issue type to track and manage local meetup organization tasks. Avoid using this issue type for tasks expected to be closed within hours.
title: "[Tracking] Cloud Native Sustainability Week <Year> <Meetup Location>"
labels: ["issue/needs-triage", "project/cloud-native-sustainability-week"]
projects: ["cncf/10"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the TAG!
        Please remember that an issue is not the place to ask questions.
        For inquiries, please refer to the README on how to reach us: [Contact](https://github.com/cncf/tag-env-sustainability#contact).
        Thank you! :)
  - id: description
    type: textarea
    attributes:
      label: Description
      description: |
        Please update these details along the way.  
      value: |
        * **Location/Region:** tbd
        * **Organizers:** tbd
        * **Sponsors:** tbd
        * **Date:** tbd
        * **Event link:** tbd
    validations:
      required: true
  - id: details
    type: textarea
    attributes:
      label: Details
      description: What are the goals and activities planned for the meetup?
    validations:
      required: true
  - id: todo-prepare
    type: checkboxes
    attributes:
      label: To-Do (Preparation)
      description: What specific actions are needed to organize this meetup?
      options:
        - label: Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
          required: true
        - label: Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
          required: true
        - label: Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
          required: false     
        - label: Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
          required: false 
        - label: Find a sponsor for the event.
          required: false   
        - label: Find a location for the event.
          required: false
        - label: Set a date for the event.
          required: false
        - label: Announce the event.
          required: false
        - label: Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.
          required: false
  - id: todo-execution
    type: checkboxes
    attributes:
      label: To-Do (During Execution)
      description: What specific actions to do during event execution?
      options:
        - label: Use the [Artworks](https://www.figma.com/design/gydAB5esFpNxO3smhZTCkl/Sustainability-Week-Layouts---Shared?node-id=8-90&node-type=canvas) and [Presentation Template](https://docs.google.com/presentation/d/15Ywyw2YjNyckXs7lEWySrjC4fh7pLglUkDZOipLDQB4/edit#slide=id.g302f22217e4_2_173). You can use some slides in the template at the begining of the event for introducing the cloud native sustainability week event.
          required: false
        - label: Distribute the feedback survey to attendees. Use the [Survey Blueprint](https://docs.google.com/forms/d/e/1FAIpQLSeIsz3T5XHhQf9ZMhfmHAchvGX5_enteQ5j9ZmIsMoFjshfGg/viewform).
          required: false
        - label: Record the event with photos or video recordings.
          required: false
  - id: todo-after
    type: checkboxes
    attributes:
      label: To-Do (After Event)
      description: What specific actions to do after the event?
      options:
        - label: Share the event records, summary via blog post, recordings to `#tag-env-cloud-native-sustainability-week` slack channel.
          required: false
        - label: Share the survey summary from attendees.
          required: false
        - label: Leave feedbacks/comments (KEEP DOING, MORE OF, START DOING, STOP DOING, LESS OF, IDEAS) about organzing the event in this issue.
          required: false
        - label: Submit the information of organizers, speakers to issue the credly badges. [to put the submission form here]
          required: false
  - id: coc
    type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.cncf.io/conduct/).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - id: comments
    type: textarea
    attributes:
      label: Comments
      description: Additional comments or details.
      placeholder: None
    validations:
        required: false
