---
name: Check

on:
  pull_request:

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: make setup

  Markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run check:markdown

  Spelling:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v3
      - name: Spelling
        run: make spelling

  Links:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v3
      - name: Links
        run: make links
