---
name: Quality Checks

on:
  pull_request:

jobs:
  run-quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: tj-actions/changed-files@v39
      id: changed-files
      with:
        files: '**/*.md'
        separator: ','

    - name: Lint Markdown files
      uses: DavidAnson/markdownlint-cli2-action@v13.0.0
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ','
        config: '.markdownlint.json' 
        fix: true
      continue-on-error: false

    - name: Validate spelling
      uses: streetsidesoftware/cspell-action@v4.0.1
      with:
        config: 'cspell.json'
        files: '**/*.md'
        inline: 'error'
        strict: true        
        incremental_files_only: true
    
    - name: Validate links in Markdown files
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
      with:
        check-modified-files-only: 'yes'
        config-file: 'link-config.json'
        base-branch: 'main'
        file-extension: '.md'
